# Generated by Django 3.2.9 on 2021-11-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211129_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
